THIRD_PARTY_NOTICES.md
pubspec.lock
pubspec.yaml

#51 :memo: adding list of dependencies

---

lib/src/locale/app_localizations.dart
lib/src/view/main/main_view.dart
lib/src/view/start/start_view.dart

About dialog now shown in both start view and in the popup menu of the main view

#54 about dialog added

---

lib/src/connect/meeting/main_websocket/main_websocket.dart
lib/src/connect/meeting/main_websocket/meeting/meeting.dart
lib/src/connect/meeting/main_websocket/meeting/model/meeting_data.dart
lib/src/locale/app_localizations.dart
lib/src/view/main/main_view.dart
lib/src/view/start/start_view.dart

#24 Supporting meeting end by moderator

---

lib/src/connect/meeting/main_websocket/user/user.dart
lib/src/connect/meeting/model/user_model.dart
lib/src/locale/app_localizations.dart
lib/src/view/main/main_view.dart
lib/src/view/meeting_info/meeting_info_view.dart

#33 Implemented user kicked by moderator

---

lib/src/connect/meeting/load/bbb_meeting_info_loader.dart
lib/src/connect/meeting/load/exception/meeting_info_load_exception.dart
lib/src/connect/meeting/load/meeting_info_loader.dart
lib/src/locale/app_localizations.dart
lib/src/view/start/start_view.dart
pubspec.lock

#65 implemented waiting rooms :sparkles:

---

lib/src/connect/meeting/main_websocket/chat/chat.dart
lib/src/view/chat/chat_view.dart
lib/src/view/start/start_view.dart
pubspec.yaml

#38 save unsent chat messages

---

THIRD_PARTY_NOTICES.md
assets/privacy_policy/de.md
assets/privacy_policy/en.md
lib/src/locale/app_localizations.dart
lib/src/view/main/main_view.dart
lib/src/view/privacy_policy/privacy_policy_view.dart
lib/src/view/start/start_view.dart
pubspec.lock
pubspec.yaml

#84 Added privacy policies

---

lib/src/broadcast/app_state_notifier.dart
lib/src/preference/preferences.dart
lib/src/view/start/start_view.dart

#60 :sparkles: saved dark mode settings in shared preferences

---

lib/src/connect/meeting/main_websocket/video/video.dart
lib/src/view/main/main_view.dart

56 loading spinners

---

lib/src/connect/meeting/main_websocket/main_websocket.dart

This might fix our #34 problem. We have to keep an eye on it if it happens again.
We are now waiting for the "validate user"-msg to be confirmed. Then we can sub to topis. Then the current user provided by the "users" topic should be filled with all info.

#34 potential fix

---

lib/src/connect/meeting/main_websocket/video/connection/outgoing_screenshare_video_connection.dart
lib/src/connect/meeting/main_websocket/video/connection/outgoing_webcam_video_connection.dart
lib/src/view/main/main_view.dart

#44 added indicator for multiple webcams

---

lib/src/connect/meeting/main_websocket/main_websocket.dart
lib/src/connect/meeting/main_websocket/user/user.dart
lib/src/utils/websocket.dart

#39 fixed logout

---

lib/src/view/fullscreen/fullscreen_view.dart
lib/src/view/main/main_view.dart
lib/src/view/main/presentation/presentation_widget.dart

57 fullscreen mode

---

lib/src/view/main/main_view.dart

Beautify: Camera Switch and Screenshare buttons are now disabled when not able to be used

---

lib/src/connect/meeting/main_websocket/presentation/model/slide/presentation_slide.dart
lib/src/connect/meeting/main_websocket/presentation/presentation.dart
lib/src/view/main/presentation/presentation_painter.dart
lib/src/view/main/presentation/presentation_svg_painter.dart
lib/src/view/main/presentation/presentation_widget.dart
pubspec.lock
pubspec.yaml

Cursorpainter

---

lib/main.dart
lib/src/connect/meeting/main_websocket/presentation/presentation.dart
lib/src/connect/meeting/main_websocket/voice/call_module.dart
lib/src/connect/meeting/voice/call_connection.dart
lib/src/connect/meeting/voice/call_manager.dart
lib/src/locale/app_localizations.dart
lib/src/utils/log.dart
lib/src/view/main/main_view.dart
lib/src/view/main/presentation/presentation_painter.dart
lib/src/view/main/presentation/presentation_svg_painter.dart
lib/src/view/main/presentation/presentation_widget.dart
lib/src/view/start/start_view.dart
pubspec.yaml

123 audio reconnect

---

lib/src/connect/meeting/main_websocket/voice/call_manager.dart
lib/src/connect/meeting/main_websocket/voice/custom_sip_ua_helper.dart
pubspec.lock
pubspec.yaml

#133 fixed

---

pubspec.lock
pubspec.yaml

#149 Updating sip_ua to 0.3.5

---

lib/src/connect/meeting/main_websocket/voice/call_manager.dart

Bugfix for passing the correct credentials to turn server

---

lib/src/connect/meeting/main_websocket/presentation/presentation.dart
lib/src/view/main/presentation/presentation_widget.dart

#141 fixed

---

lib/src/connect/meeting/main_websocket/chat/chat.dart
lib/src/connect/meeting/main_websocket/main_websocket.dart
lib/src/connect/meeting/main_websocket/user/model/user.dart
lib/src/connect/meeting/main_websocket/user/user_module.dart
lib/src/connect/meeting/main_websocket/video/connection/incoming_video_connection.dart
lib/src/connect/meeting/main_websocket/video/connection/outgoing_screenshare_video_connection.dart
lib/src/connect/meeting/main_websocket/video/connection/outgoing_webcam_video_connection.dart
lib/src/connect/meeting/main_websocket/video/connection/video_connection.dart
lib/src/connect/meeting/main_websocket/video/video.dart
lib/src/connect/meeting/main_websocket/voice/call_module.dart
lib/src/connect/meeting/main_websocket/voice/voice_users.dart
lib/src/view/chat/chat_view.dart
lib/src/view/fullscreen/fullscreen_view.dart
lib/src/view/main/main_view.dart
lib/src/view/meeting_info/meeting_info_view.dart
lib/src/view/start/start_view.dart

Closes #156 and webcam sharing related problems causing a crash.

156 audio connected twice

---

lib/src/connect/meeting/main_websocket/chat/chat.dart
lib/src/connect/meeting/main_websocket/chat/message.dart
lib/src/connect/meeting/main_websocket/main_websocket.dart
lib/src/connect/meeting/main_websocket/user/user_module.dart
lib/src/connect/meeting/main_websocket/voice/voice_users.dart
lib/src/locale/app_localizations.dart
lib/src/view/chat/chat_view.dart
lib/src/view/main/main_view.dart

Fixed #173, #174, #175, #176

---

lib/src/connect/meeting/main_websocket/chat/chat.dart
lib/src/connect/meeting/main_websocket/main_websocket.dart
lib/src/connect/meeting/main_websocket/user/model/user.dart
lib/src/connect/meeting/main_websocket/user/user_module.dart
lib/src/connect/meeting/main_websocket/video/video.dart
lib/src/connect/meeting/main_websocket/voice/voice_users.dart
lib/src/view/chat/chat_view.dart
lib/src/view/main/main_view.dart
lib/src/view/meeting_info/meeting_info_view.dart

Fixed #178 - Missing indication about who is currently talking

---

lib/src/connect/meeting/main_websocket/main_websocket.dart
lib/src/connect/meeting/main_websocket/voice/voice_users.dart
lib/src/view/meeting_info/meeting_info_view.dart

#124 Added audio status to participant list + fixed #172
